name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - run: cd infrastructure && npm install

      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          cloud-url: 'gs://garstecki-pulumi'
          work-dir: infrastructure
