name: Deploy

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  job_id:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'

      - id: 'url'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
