name: Deploy

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          image_url: gcr.io/high-plating-318219/gcp:latest
